package app.domain.models.game;

public enum GameState {
    LOADING_STATE,
    BUILDING_STATE,
    DISTRIBUTING_STATE,
    RECEIVING_STATE,
    REPLACEMENT_STATE,
    TRADE_CARD_STATE,
    ATTACK_STATE,
    FORTIFY_STATE,
    GAME_OVER_STATE;
}
